In [1]:
#load dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os

path = "../data/raw/*.csv"

files = glob.glob(path)

files

['../data/raw\\IoTpond1.csv',
 '../data/raw\\IoTPond10.csv',
 '../data/raw\\IoTPond11.csv',
 '../data/raw\\IoTPond12.csv',
 '../data/raw\\IoTPond2.csv',
 '../data/raw\\IoTPond3.csv',
 '../data/raw\\IoTPond4.csv',
 '../data/raw\\IoTPond6.csv',
 '../data/raw\\IoTPond7.csv',
 '../data/raw\\IoTPond8.csv',
 '../data/raw\\IoTPond9.csv']

In [2]:
#merge 12 pond datasets into 1
import os

dataframes = []

for file in files:
    
    df = pd.read_csv(file)

    filename = os.path.basename(file)

    pond_number = ''.join(filter(str.isdigit, filename))

    df["pond"] = pond_number

    dataframes.append(df)

data = pd.concat(dataframes, ignore_index=True)

data.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_19380\713060728.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_19380\713060728.py:8: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_19380\713060728.py:8: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

,created_at,entry_id,Temperature (C),Turbidity(NTU),Dissolved Oxygen(g/ml),PH,Ammonia(g/ml),Nitrate(g/ml),Population,Fish_Length(cm),...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 0,Dissolved Oxygen (mg/L),Ammonia (mg/L),Nitrate (mg/L),Total_length (cm),Weight (g),DATE
0,2021-06-19 00:00:05 CET,1889.0,24.8750,100.0,4.505,8.43365,0.45842,193.0,50.0,7.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-06-19 00:01:02 CET,1890.0,24.9375,100.0,6.601,8.43818,0.45842,194.0,50.0,7.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-06-19 00:01:22 CET,1891.0,24.8750,100.0,15.797,8.42457,0.45842,192.0,50.0,7.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-06-19 00:01:44 CET,1892.0,24.9375,100.0,5.046,8.43365,0.45842,193.0,50.0,7.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-06-19 00:02:07 CET,1893.0,24.9375,100.0,38.407,8.40641,0.45842,192.0,50.0,7.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.shape

(1114970, 43)

In [4]:
#saved in process folder
data.to_csv("../data/processed/combined_pond_dataset.csv", index=False)

PREPROCESS DATA

In [5]:
data.columns

Index(['created_at', 'entry_id', 'Temperature (C)', 'Turbidity(NTU)',
       'Dissolved Oxygen(g/ml)', 'PH', 'Ammonia(g/ml)', 'Nitrate(g/ml)',
       'Population', 'Fish_Length(cm)', 'Fish_Weight(g)', 'pond',
       'TEMPERATURE', 'TURBIDITY', 'DISOLVED OXYGEN', 'pH', 'AMMONIA',
       'NITRATE', 'Length', 'Weight', 'Lenght', 'Turbidity (NTU)',
       'Fish_Length (cm)', 'Fish_Weight (g)', 'Temperature(C)', 'Date',
       'temperature(C)', 'turbidity (NTU)', 'Dissolved Oxygen (g/ml)',
       'ammonia(g/ml)', 'nitrate(g/ml)', 'Fish_length(cm)', 'Fish_weight(g)',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 0',
       'Dissolved Oxygen (mg/L)', 'Ammonia (mg/L)', 'Nitrate (mg/L)',
       'Total_length (cm)', 'Weight (g)', 'DATE'],
      dtype='object')

DATA CLEANING

In [6]:
data.columns = data.columns.str.lower()
data.columns
[c for c in data.columns if "temp" in c]
[c for c in data.columns if "turb" in c]
[c for c in data.columns if "oxygen" in c]
[c for c in data.columns if "ammo" in c]
[c for c in data.columns if "nitra" in c]

['nitrate(g/ml)', 'nitrate', 'nitrate(g/ml)', 'nitrate (mg/l)']

In [7]:
data["temperature"] = data.filter(like="temp").iloc[:,0]
data["turbidity"] = data.filter(like="turb").iloc[:,0]
data["dissolved_oxygen"] = data.filter(like="oxygen").iloc[:,0]
data["ph"] = data.filter(like="ph").iloc[:,0]
data["ammonia"] = data.filter(like="ammo").iloc[:,0]
data["nitrate"] = data.filter(like="nitra").iloc[:,0]

In [8]:
data = data[[
    "created_at",
    "temperature",
    "turbidity",
    "dissolved_oxygen",
    "ph",
    "ammonia",
    "nitrate",
    "pond"
]]
data.head()

,created_at,temperature,turbidity,dissolved_oxygen,ph,ph,ammonia,nitrate,pond
0,2021-06-19 00:00:05 CET,24.8750,100.0,4.505,8.43365,8.43365,0.45842,193.0,1
1,2021-06-19 00:01:02 CET,24.9375,100.0,6.601,8.43818,8.43818,0.45842,194.0,1
2,2021-06-19 00:01:22 CET,24.8750,100.0,15.797,8.42457,8.42457,0.45842,192.0,1
3,2021-06-19 00:01:44 CET,24.9375,100.0,5.046,8.43365,8.43365,0.45842,193.0,1
4,2021-06-19 00:02:07 CET,24.9375,100.0,38.407,8.40641,8.40641,0.45842,192.0,1

EDA 2.0

In [9]:
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1114970 entries, 0 to 1114969
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   created_at        1044225 non-null  object
 1   temperature       326119 non-null   float64
 2   turbidity         655652 non-null   float64
 3   dissolved_oxygen  757157 non-null   float64
 4   ph                1107513 non-null  float64
 5   ph                1107513 non-null  float64
 6   ammonia           756853 non-null   float64
 7   nitrate           757157 non-null   float64
 8   pond              1114970 non-null  object
dtypes: float64(7), object(2)
memory usage: 76.6+ MB

In [10]:
#check for missing values
data.isnull().sum()
#if missing, interpolate and type this command data = data.interpolate(numeric_only=True)
# if >0 = missing values

created_at           70745
temperature         788851
turbidity           459318
dissolved_oxygen    357813
ph                    7457
ph                    7457
ammonia             358117
nitrate             357813
pond                     0
dtype: int64

In [11]:
#interpolate for missing values 1.1
data.dtypes

created_at           object
temperature         float64
turbidity           float64
dissolved_oxygen    float64
ph                  float64
ph                  float64
ammonia             float64
nitrate             float64
pond                 object
dtype: object

In [12]:
#interpolate for missing values 1.2
data = data.loc[:, ~data.columns.duplicated()]

In [13]:
data["created_at"] = pd.to_datetime(data["created_at"], errors="coerce", utc=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_19380\1979743551.py:1: FutureWarning: Parsed string "2021-06-19 00:00:05 CET" included an un-recognized timezone "CET". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  data["created_at"] = pd.to_datetime(data["created_at"], errors="coerce", utc=True)

In [14]:
data.dtypes

created_at          datetime64[ns, UTC]
temperature                     float64
turbidity                       float64
dissolved_oxygen                float64
ph                              float64
ammonia                         float64
nitrate                         float64
pond                             object
dtype: object

EDA

In [15]:
#SORT TIME SERIES
data = data.sort_values("created_at")

In [16]:

#CHECK AGAIN FOR MISSING VALUES (PAGOD NA KO HAYS...)
data.isnull().sum()

created_at          288340
temperature         788851
turbidity           459318
dissolved_oxygen    357813
ph                    7457
ammonia             358117
nitrate             357813
pond                     0
dtype: int64

In [17]:
#interpolate missi
numeric_cols = [
    "temperature",
    "turbidity",
    "dissolved_oxygen",
    "ph",
    "ammonia",
    "nitrate"
]

data[numeric_cols] = data[numeric_cols].interpolate()

In [18]:
data = data.dropna(subset=["created_at"])

In [19]:
#interpolation successful, no more missing values
data.isnull().sum()

created_at             0
temperature         2921
turbidity              0
dissolved_oxygen       0
ph                     0
ammonia                0
nitrate                0
pond                   0
dtype: int64

In [20]:
#current dataset size
data.shape

(826630, 8)

In [21]:
data.to_csv("../data/processed/combined_pond_dataset.csv", index=False)